spring:
  datasource:
    url: jdbc:mysql://192.168.31.101:3306/common_auth?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: young
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver